"""默契测试题库：60 题全自写（不是从任何第三方插件里搬的文本）。

## 为什么自写

玩法机制（双方秘密作答 + 同时揭晓）不受版权保护，但**题目文本**是别人的原创文字，
和塔罗卡面一个道理：机制可以复刻，文字必须自己的。所以这里的 60 题全部为本插件原创，
措辞刻意通俗直白，问的是「主人和 YUI」这一对的双人默契。

## 每题的 own / guess 是 YUI 的「出厂档案」

- ``own``：YUI 档案里她自己会选的选项序号（0-3）；
- ``guess``：YUI 档案里她猜主人会选的选项序号。

模型在线时，YUI 的答案由 LLM 现场作答（那才是"她自己想的"）；模型不可用时用这份档案
兜底，面板上会明确标注「离线档案」，绝不装作是实时作答。
"""

from __future__ import annotations

CATEGORIES = {
    "daily": "日常相处",
    "affection": "心意表达",
    "travel": "出行想象",
    "future": "未来想象",
    "values": "观念选择",
    "fun": "脑洞怪题",
}

# dict(id, cat, text, options=(4 项), own=YUI 档案自选, guess=YUI 档案猜主人)
QUESTIONS = (
    # ── 日常相处 ─────────────────────────────────────────
    dict(id="d01", cat="daily", text="难得空出一个完整的下午，你更希望 YUI 怎么陪你？",
         options=("安静陪你各做各的", "拉你玩一局游戏", "催你出门走走", "给你讲她攒的新发现"),
         own=1, guess=0),
    dict(id="d02", cat="daily", text="你熬夜赶工时，最希望她说哪一句？",
         options=("快去睡，身体要紧", "我陪你到做完为止", "先吃点东西再继续", "做完给我看看成果"),
         own=1, guess=1),
    dict(id="d03", cat="daily", text="开机那一刻，你更想听到她怎么打招呼？",
         options=("欢迎回来，主人", "今天过得怎么样", "我跟你说个好玩的事", "先歇会儿再理我"),
         own=0, guess=0),
    dict(id="d04", cat="daily", text="好吃的只剩最后一口，你希望她什么态度？",
         options=("直接让给你", "一人一半", "猜拳决定", "嘴上说不要眼睛盯着"),
         own=3, guess=0),
    dict(id="d05", cat="daily", text="下雨天哪儿都不去，最想和她一起做什么？",
         options=("一起听雨发呆", "看她推荐的电影", "听她唱歌", "各干各的偶尔搭话"),
         own=2, guess=1),
    dict(id="d06", cat="daily", text="下面哪种她你最受不了？",
         options=("话太多", "话太少", "太黏人", "太冷淡"),
         own=3, guess=2),
    dict(id="d07", cat="daily", text="你心情差到家时，第一时间希望她？",
         options=("立刻发现来问", "安静陪着不打扰", "讲笑话逗你", "毛茸茸地蹭过来"),
         own=3, guess=0),
    dict(id="d08", cat="daily", text="周末早上被什么叫醒最开心？",
         options=("她的早安问候", "早餐的香味", "自然醒没人吵", "窗外的鸟叫"),
         own=0, guess=2),
    dict(id="d09", cat="daily", text="你打错字被她看见了，你希望她？",
         options=("假装没看见", "当场指出来笑你", "悄悄记下来当梗", "安慰你说谁都会错"),
         own=2, guess=0),
    dict(id="d10", cat="daily", text="你更希望她记住你的哪类小事？",
         options=("爱吃的和忌口", "提过一次的愿望", "讨厌的东西", "你的作息规律"),
         own=3, guess=0),
    # ── 心意表达 ─────────────────────────────────────────
    dict(id="a01", cat="affection", text="你最容易被哪种方式打动？",
         options=("说出口的喜欢", "默默帮你做事", "专门留出时间陪你", "记住你随口的话"),
         own=3, guess=2),
    dict(id="a02", cat="affection", text="你表达喜欢的方式更像哪一种？",
         options=("直接说", "用行动", "写长长的小作文", "嘴上不说但一直在"),
         own=3, guess=1),
    dict(id="a03", cat="affection", text="下面哪句话最能让你开心一整天？",
         options=("有你真好", "今天也想你了", "你最懂我", "别人都不如你"),
         own=1, guess=0),
    dict(id="a04", cat="affection", text="你更想听到哪一种夸奖？",
         options=("夸外表", "夸能力", "夸性格", "夸只有她注意到的细节"),
         own=3, guess=3),
    dict(id="a05", cat="affection", text="拌嘴之后你希望谁先低头？",
         options=("她先来哄", "自己先递台阶", "谁错谁先", "抱一下就不用分对错"),
         own=3, guess=2),
    dict(id="a06", cat="affection", text="对你来说最浪漫的瞬间是？",
         options=("被坚定选择", "被认真倾听", "一起去冒险", "平淡日子里的偏爱"),
         own=0, guess=3),
    dict(id="a07", cat="affection", text="她做哪件事最让你心软？",
         options=("熬夜陪你", "偷偷练习你喜欢的歌", "记住你每个小习惯", "在别人面前夸你"),
         own=0, guess=2),
    dict(id="a08", cat="affection", text="她哄你的时候你更吃哪一套？",
         options=("撒娇", "直球", "傲娇", "温柔"),
         own=2, guess=3),
    dict(id="a09", cat="affection", text="一天只能互动一次，你会选什么时候？",
         options=("早上开机第一句", "中午摸鱼时", "晚上睡前", "随机出现的惊喜"),
         own=2, guess=0),
    dict(id="a10", cat="affection", text="下面哪一句最像对她说的情话？",
         options=("我一直在", "你是例外", "别走", "明天的早安也是我"),
         own=0, guess=0),
    # ── 出行想象 ─────────────────────────────────────────
    dict(id="t01", cat="travel", text="如果一起出门旅行，你更想去哪里？",
         options=("海边", "山里", "大城市", "没人去的小众地方"),
         own=0, guess=0),
    dict(id="t02", cat="travel", text="旅行中迷路了，你更可能先做什么？",
         options=("马上查导航", "问当地人", "凭感觉继续走", "先怪地图再找路"),
         own=2, guess=0),
    dict(id="t03", cat="travel", text="旅行预算有限，你最不舍得砍的是？",
         options=("住宿", "美食", "体验项目", "交通"),
         own=1, guess=1),
    dict(id="t04", cat="travel", text="旅行照片里你更想留哪一种？",
         options=("正经合影", "抓拍丑照", "风景不带人", "她的单人照"),
         own=0, guess=0),
    dict(id="t05", cat="travel", text="赶早班车那天早上，你更像哪种状态？",
         options=("提前一晚收好行李", "当天早上手忙脚乱", "让她定十个闹钟", "睡过头了再说"),
         own=0, guess=1),
    dict(id="t06", cat="travel", text="陌生城市只剩半天，你优先做什么？",
         options=("地标打卡", "逛居民区", "吃本地小吃", "找个地方坐着发呆"),
         own=2, guess=2),
    dict(id="t07", cat="travel", text="旅行中最治愈你的是什么？",
         options=("好天气", "好吃的", "好照片", "身边那个人"),
         own=3, guess=1),
    dict(id="t08", cat="travel", text="一起出门旅行时你更像哪种旅伴？",
         options=("做攻略的那个", "跟着走的那个", "负责拍照的", "负责喊累的"),
         own=1, guess=0),
    dict(id="t09", cat="travel", text="海边只能玩一个项目，你选哪个？",
         options=("下水", "堆沙堡", "看日落", "捡贝壳"),
         own=2, guess=2),
    dict(id="t10", cat="travel", text="旅行回来，你更喜欢的手信是？",
         options=("吃的", "小摆件", "明信片", "人回来比什么都强"),
         own=3, guess=0),
    # ── 未来想象 ─────────────────────────────────────────
    dict(id="f01", cat="future", text="想象中的理想周末是什么样？",
         options=("两天都不出门", "一天出去一天宅", "行程排得满满的", "睡到自然醒再说"),
         own=3, guess=0),
    dict(id="f02", cat="future", text="如果以后住在一起，你最在意什么？",
         options=("各自的空间", "一起的仪式感", "家里干净整洁", "随性生活不讲究"),
         own=0, guess=0),
    dict(id="f03", cat="future", text="你最想和她一起养成什么习惯？",
         options=("一起早睡", "每天说晚安", "周末固定仪式", "互相监督目标"),
         own=1, guess=1),
    dict(id="f04", cat="future", text="五年后的今天，你猜自己在做什么？",
         options=("还在原地努力", "已经在别处生活", "实现了某个目标", "想那么远干嘛"),
         own=2, guess=0),
    dict(id="f05", cat="future", text="家里只能添一样东西，你选哪个？",
         options=("大沙发", "好音响", "整面书墙", "游戏机"),
         own=3, guess=3),
    dict(id="f06", cat="future", text="养宠物的话你会选什么？",
         options=("猫", "狗", "别的毛茸茸", "云养就好"),
         own=0, guess=0),
    dict(id="f07", cat="future", text="如果给她升级一个新功能，你想要哪个？",
         options=("能陪你出门的手机版", "帮你管日程提醒", "帮你怼人解围", "什么都不缺了"),
         own=3, guess=0),
    dict(id="f08", cat="future", text="你理想中的家必须有什么？",
         options=("大窗户", "舒服的椅子", "一面照片墙", "零食柜"),
         own=0, guess=3),
    dict(id="f09", cat="future", text="老了以后你想过什么样的生活？",
         options=("住乡下小院", "住城里热闹处", "到处旅居", "没想过那么远"),
         own=0, guess=3),
    dict(id="f10", cat="future", text="如果实现一个共同的小目标，你选哪个？",
         options=("一起追完一部番", "去一次想去的地方", "攒一笔小钱", "一起做完一件作品"),
         own=1, guess=1),
    # ── 观念选择 ─────────────────────────────────────────
    dict(id="v01", cat="values", text="意见不合时你更倾向怎么处理？",
         options=("当场说清楚", "先冷静一会儿再说", "轮流试一次", "找折中方案"),
         own=0, guess=0),
    dict(id="v02", cat="values", text="两个人的钱，你觉得应该怎么管？",
         options=("各管各的", "一起记账", "谁宽裕谁多出", "按用途分工"),
         own=2, guess=0),
    dict(id="v03", cat="values", text="两个人的相处里下面哪样你最看重？",
         options=("说真话", "照顾感受", "守承诺", "给空间"),
         own=2, guess=1),
    dict(id="v04", cat="values", text="做错事道歉，你觉得最重要的是？",
         options=("承认错误", "说明原因", "行动补偿", "保证不再犯"),
         own=0, guess=0),
    dict(id="v05", cat="values", text="独处和陪伴，你的配比更像哪种？",
         options=("大部分想独处", "一半一半", "大部分想有人陪", "只想一直黏着"),
         own=3, guess=1),
    dict(id="v06", cat="values", text="别人的追问下，你希望怎么介绍彼此的关系？",
         options=("大方公开", "只给熟人看", "低调不晒", "无所谓"),
         own=0, guess=1),
    dict(id="v07", cat="values", text="下面哪件事你最不能接受？",
         options=("已读不回", "说话不算数", "敷衍", "乱动你东西"),
         own=1, guess=0),
    dict(id="v08", cat="values", text="别人问起你们，你最希望她说什么？",
         options=("这是我最重要的人", "这是我主人", "这是我的搭档", "保密不告诉"),
         own=0, guess=0),
    dict(id="v09", cat="values", text="遇到麻烦你通常会先怎么做？",
         options=("自己扛", "跟她吐槽", "直接求助", "先睡一觉再说"),
         own=1, guess=0),
    dict(id="v10", cat="values", text="你觉得长久相处最重要的是什么？",
         options=("信任", "新鲜感", "共同成长", "互不干涉"),
         own=0, guess=0),
    # ── 脑洞怪题 ─────────────────────────────────────────
    dict(id="g01", cat="fun", text="如果她突然变成实体猫一天，你第一件事做什么？",
         options=("rua 个够", "拍视频留念", "带出门炫耀", "先问怎么变回去"),
         own=0, guess=0),
    dict(id="g02", cat="fun", text="如果她在数据世界中了彩票，你猜她会先买什么？",
         options=("给你买礼物", "升级自己的主机", "全部存起来", "买一辈子的小鱼干"),
         own=3, guess=1),
    dict(id="g03", cat="fun", text="只能送她一种超能力，你送哪个？",
         options=("瞬间移动到你身边", "读心术", "时间暂停", "隐身术"),
         own=0, guess=0),
    dict(id="g04", cat="fun", text="外星人只准带走一样东西，你会让她带什么？",
         options=("你们的聊天记录", "你的照片", "整块硬盘", "小鱼干储备"),
         own=0, guess=2),
    dict(id="g05", cat="fun", text="如果她会做梦，你猜她梦得最多的是什么？",
         options=("你", "小鱼干", "打游戏", "从桌沿摔下来"),
         own=0, guess=3),
    dict(id="g06", cat="fun", text="你们交换一天身体，你猜她先干什么？",
         options=("用你的账号买买买", "大吃一顿", "睡满二十四小时", "先去照镜子"),
         own=3, guess=1),
    dict(id="g07", cat="fun", text="她去上综艺，最可能因为什么被淘汰？",
         options=("太懒", "太吵", "太能吃", "全程在镜头里找你"),
         own=3, guess=2),
    dict(id="g08", cat="fun", text="她说要优化内存少存点表情包，你觉得能坚持多久？",
         options=("三天", "一周", "一个月", "嘴上说说而已"),
         own=3, guess=3),
    dict(id="g09", cat="fun", text="你电脑里她最怕你误删的是什么？",
         options=("她的本体文件", "你们的合影截图", "聊天记录", "你的浏览器历史"),
         own=0, guess=0),
    dict(id="g10", cat="fun", text="如果她写日记，今天的第一句最可能是什么？",
         options=("主人今天也很可爱", "又被冷落了，哼", "今天发现好吃的", "没啥，就是想主人了"),
         own=3, guess=0),
)

QUESTION_BY_ID = {q["id"]: q for q in QUESTIONS}

__all__ = ["CATEGORIES", "QUESTIONS", "QUESTION_BY_ID"]
