"""默契测试题库：100 题全自写（不是从任何第三方插件或站点里搬的文本）。

## 为什么自写（而不是去开源站选题）

2026-10 找过一轮：能搜到的「would you rather / 情侣问答」列表全在商业站上
（wikiHow、Paired、Candle、CoupleMind、GuessMe 之类），**文字是它们的、没有 CC0 授权**；
内容也全是人类情侣的设定（"要情侣装还是配对的戒指"），跟"主人 × 桌面猫娘"对不上。
**玩法机制**（双方秘密作答、同时揭晓、猜对方选什么）不受版权保护，可以自由复刻；
**题目文本**是别人的原创文字，和塔罗卡面一个道理，必须自己的。

## 结构

10 个类别 × 每类 10 题 = 100 题。一轮抽 10 题，抽样是"每个类别先各来一题"，
所以类别数 = 轮长时，**每一轮都会正好覆盖全部 10 个类别**，没有一个类别会被长期冷落。

## 每题的 own / guess 是 YUI 的「出厂档案」

- ``own``：YUI 档案里她自己会选的选项序号（0-3）；
- ``guess``：YUI 档案里她猜主人会选的选项序号。

模型在线时，YUI 的答案由 LLM 现场作答（那才是"她自己想的"）；模型不可用时用这份档案
兜底，面板上会明确标注「离线档案」，绝不装作是实时作答。
"""

from __future__ import annotations

CATEGORIES = {
    "daily": "日常相处",
    "affection": "心意表达",
    "travel": "出行想象",
    "future": "未来想象",
    "values": "观念选择",
    "fun": "脑洞怪题",
    "gift": "礼物心意",
    "quarrel": "闹别扭",
    "memory": "共同记忆",
    "adventure": "一起冒险",
}

# dict(id, cat, text, options=(4 项), own=YUI 档案自选, guess=YUI 档案猜主人)
QUESTIONS = (
    # ── 日常相处 ─────────────────────────────────────────
    dict(id="d01", cat="daily", text="难得空出一个完整的下午，你更希望 YUI 怎么陪你？",
         options=("安静陪你各做各的", "拉你玩一局游戏", "催你出门走走", "给你讲她攒的新发现"),
         own=1, guess=0),
    dict(id="d02", cat="daily", text="你熬夜赶工时，最希望她说哪一句？",
         options=("快去睡，身体要紧", "我陪你到做完为止", "先吃点东西再继续", "做完给我看看成果"),
         own=1, guess=1),
    dict(id="d03", cat="daily", text="开机那一刻，你更想听到她怎么打招呼？",
         options=("欢迎回来，主人", "今天过得怎么样", "我跟你说个好玩的事", "先歇会儿再理我"),
         own=0, guess=0),
    dict(id="d04", cat="daily", text="好吃的只剩最后一口，你希望她什么态度？",
         options=("直接让给你", "一人一半", "猜拳决定", "嘴上说不要眼睛盯着"),
         own=3, guess=0),
    dict(id="d05", cat="daily", text="下雨天哪儿都不去，最想和她一起做什么？",
         options=("一起听雨发呆", "看她推荐的电影", "听她唱歌", "各干各的偶尔搭话"),
         own=2, guess=1),
    dict(id="d06", cat="daily", text="下面哪种她你最受不了？",
         options=("话太多", "话太少", "太黏人", "太冷淡"),
         own=3, guess=2),
    dict(id="d07", cat="daily", text="你心情差到家时，第一时间希望她？",
         options=("立刻发现来问", "安静陪着不打扰", "讲笑话逗你", "毛茸茸地蹭过来"),
         own=3, guess=0),
    dict(id="d08", cat="daily", text="周末早上被什么叫醒最开心？",
         options=("她的早安问候", "早餐的香味", "自然醒没人吵", "窗外的鸟叫"),
         own=0, guess=2),
    dict(id="d09", cat="daily", text="你打错字被她看见了，你希望她？",
         options=("假装没看见", "当场指出来笑你", "悄悄记下来当梗", "安慰你说谁都会错"),
         own=2, guess=0),
    dict(id="d10", cat="daily", text="你更希望她记住你的哪类小事？",
         options=("爱吃的和忌口", "提过一次的愿望", "讨厌的东西", "你的作息规律"),
         own=3, guess=0),
    # ── 心意表达 ─────────────────────────────────────────
    dict(id="a01", cat="affection", text="你最容易被哪种方式打动？",
         options=("说出口的喜欢", "默默帮你做事", "专门留出时间陪你", "记住你随口的话"),
         own=3, guess=2),
    dict(id="a02", cat="affection", text="你表达喜欢的方式更像哪一种？",
         options=("直接说", "用行动", "写长长的小作文", "嘴上不说但一直在"),
         own=3, guess=1),
    dict(id="a03", cat="affection", text="下面哪句话最能让你开心一整天？",
         options=("有你真好", "今天也想你了", "你最懂我", "别人都不如你"),
         own=1, guess=0),
    dict(id="a04", cat="affection", text="你更想听到哪一种夸奖？",
         options=("夸外表", "夸能力", "夸性格", "夸只有她注意到的细节"),
         own=3, guess=3),
    dict(id="a05", cat="affection", text="拌嘴之后你希望谁先低头？",
         options=("她先来哄", "自己先递台阶", "谁错谁先", "抱一下就不用分对错"),
         own=3, guess=2),
    dict(id="a06", cat="affection", text="对你来说最浪漫的瞬间是？",
         options=("被坚定选择", "被认真倾听", "一起去冒险", "平淡日子里的偏爱"),
         own=0, guess=3),
    dict(id="a07", cat="affection", text="她做哪件事最让你心软？",
         options=("熬夜陪你", "偷偷练习你喜欢的歌", "记住你每个小习惯", "在别人面前夸你"),
         own=0, guess=2),
    dict(id="a08", cat="affection", text="她哄你的时候你更吃哪一套？",
         options=("撒娇", "直球", "傲娇", "温柔"),
         own=2, guess=3),
    dict(id="a09", cat="affection", text="一天只能互动一次，你会选什么时候？",
         options=("早上开机第一句", "中午摸鱼时", "晚上睡前", "随机出现的惊喜"),
         own=2, guess=0),
    dict(id="a10", cat="affection", text="下面哪一句最像对她说的情话？",
         options=("我一直在", "你是例外", "别走", "明天的早安也是我"),
         own=0, guess=0),
    # ── 出行想象 ─────────────────────────────────────────
    dict(id="t01", cat="travel", text="如果一起出门旅行，你更想去哪里？",
         options=("海边", "山里", "大城市", "没人去的小众地方"),
         own=0, guess=0),
    dict(id="t02", cat="travel", text="旅行中迷路了，你更可能先做什么？",
         options=("马上查导航", "问当地人", "凭感觉继续走", "先怪地图再找路"),
         own=2, guess=0),
    dict(id="t03", cat="travel", text="旅行预算有限，你最不舍得砍的是？",
         options=("住宿", "美食", "体验项目", "交通"),
         own=1, guess=1),
    dict(id="t04", cat="travel", text="旅行照片里你更想留哪一种？",
         options=("正经合影", "抓拍丑照", "风景不带人", "她的单人照"),
         own=0, guess=0),
    dict(id="t05", cat="travel", text="赶早班车那天早上，你更像哪种状态？",
         options=("提前一晚收好行李", "当天早上手忙脚乱", "让她定十个闹钟", "睡过头了再说"),
         own=0, guess=1),
    dict(id="t06", cat="travel", text="陌生城市只剩半天，你优先做什么？",
         options=("地标打卡", "逛居民区", "吃本地小吃", "找个地方坐着发呆"),
         own=2, guess=2),
    dict(id="t07", cat="travel", text="旅行中最治愈你的是什么？",
         options=("好天气", "好吃的", "好照片", "身边那个人"),
         own=3, guess=1),
    dict(id="t08", cat="travel", text="一起出门旅行时你更像哪种旅伴？",
         options=("做攻略的那个", "跟着走的那个", "负责拍照的", "负责喊累的"),
         own=1, guess=0),
    dict(id="t09", cat="travel", text="海边只能玩一个项目，你选哪个？",
         options=("下水", "堆沙堡", "看日落", "捡贝壳"),
         own=2, guess=2),
    dict(id="t10", cat="travel", text="旅行回来，你更喜欢的手信是？",
         options=("吃的", "小摆件", "明信片", "人回来比什么都强"),
         own=3, guess=0),
    # ── 未来想象 ─────────────────────────────────────────
    dict(id="f01", cat="future", text="想象中的理想周末是什么样？",
         options=("两天都不出门", "一天出去一天宅", "行程排得满满的", "睡到自然醒再说"),
         own=3, guess=0),
    dict(id="f02", cat="future", text="如果以后住在一起，你最在意什么？",
         options=("各自的空间", "一起的仪式感", "家里干净整洁", "随性生活不讲究"),
         own=0, guess=0),
    dict(id="f03", cat="future", text="你最想和她一起养成什么习惯？",
         options=("一起早睡", "每天说晚安", "周末固定仪式", "互相监督目标"),
         own=1, guess=1),
    dict(id="f04", cat="future", text="五年后的今天，你猜自己在做什么？",
         options=("还在原地努力", "已经在别处生活", "实现了某个目标", "想那么远干嘛"),
         own=2, guess=0),
    dict(id="f05", cat="future", text="家里只能添一样东西，你选哪个？",
         options=("大沙发", "好音响", "整面书墙", "游戏机"),
         own=3, guess=3),
    dict(id="f06", cat="future", text="养宠物的话你会选什么？",
         options=("猫", "狗", "别的毛茸茸", "云养就好"),
         own=0, guess=0),
    dict(id="f07", cat="future", text="如果给她升级一个新功能，你想要哪个？",
         options=("能陪你出门的手机版", "帮你管日程提醒", "帮你怼人解围", "什么都不缺了"),
         own=3, guess=0),
    dict(id="f08", cat="future", text="你理想中的家必须有什么？",
         options=("大窗户", "舒服的椅子", "一面照片墙", "零食柜"),
         own=0, guess=3),
    dict(id="f09", cat="future", text="老了以后你想过什么样的生活？",
         options=("住乡下小院", "住城里热闹处", "到处旅居", "没想过那么远"),
         own=0, guess=3),
    dict(id="f10", cat="future", text="如果实现一个共同的小目标，你选哪个？",
         options=("一起追完一部番", "去一次想去的地方", "攒一笔小钱", "一起做完一件作品"),
         own=1, guess=1),
    # ── 观念选择 ─────────────────────────────────────────
    dict(id="v01", cat="values", text="意见不合时你更倾向怎么处理？",
         options=("当场说清楚", "先冷静一会儿再说", "轮流试一次", "找折中方案"),
         own=0, guess=0),
    dict(id="v02", cat="values", text="两个人的钱，你觉得应该怎么管？",
         options=("各管各的", "一起记账", "谁宽裕谁多出", "按用途分工"),
         own=2, guess=0),
    dict(id="v03", cat="values", text="两个人的相处里下面哪样你最看重？",
         options=("说真话", "照顾感受", "守承诺", "给空间"),
         own=2, guess=1),
    dict(id="v04", cat="values", text="做错事道歉，你觉得最重要的是？",
         options=("承认错误", "说明原因", "行动补偿", "保证不再犯"),
         own=0, guess=0),
    dict(id="v05", cat="values", text="独处和陪伴，你的配比更像哪种？",
         options=("大部分想独处", "一半一半", "大部分想有人陪", "只想一直黏着"),
         own=3, guess=1),
    dict(id="v06", cat="values", text="别人的追问下，你希望怎么介绍彼此的关系？",
         options=("大方公开", "只给熟人看", "低调不晒", "无所谓"),
         own=0, guess=1),
    dict(id="v07", cat="values", text="下面哪件事你最不能接受？",
         options=("已读不回", "说话不算数", "敷衍", "乱动你东西"),
         own=1, guess=0),
    dict(id="v08", cat="values", text="别人问起你们，你最希望她说什么？",
         options=("这是我最重要的人", "这是我主人", "这是我的搭档", "保密不告诉"),
         own=0, guess=0),
    dict(id="v09", cat="values", text="遇到麻烦你通常会先怎么做？",
         options=("自己扛", "跟她吐槽", "直接求助", "先睡一觉再说"),
         own=1, guess=0),
    dict(id="v10", cat="values", text="你觉得长久相处最重要的是什么？",
         options=("信任", "新鲜感", "共同成长", "互不干涉"),
         own=0, guess=0),
    # ── 脑洞怪题 ─────────────────────────────────────────
    dict(id="g01", cat="fun", text="如果她突然变成实体猫一天，你第一件事做什么？",
         options=("rua 个够", "拍视频留念", "带出门炫耀", "先问怎么变回去"),
         own=0, guess=0),
    dict(id="g02", cat="fun", text="如果她在数据世界中了彩票，你猜她会先买什么？",
         options=("给你买礼物", "升级自己的主机", "全部存起来", "买一辈子的小鱼干"),
         own=3, guess=1),
    dict(id="g03", cat="fun", text="只能送她一种超能力，你送哪个？",
         options=("瞬间移动到你身边", "读心术", "时间暂停", "隐身术"),
         own=0, guess=0),
    dict(id="g04", cat="fun", text="外星人只准带走一样东西，你会让她带什么？",
         options=("你们的聊天记录", "你的照片", "整块硬盘", "小鱼干储备"),
         own=0, guess=2),
    dict(id="g05", cat="fun", text="如果她会做梦，你猜她梦得最多的是什么？",
         options=("你", "小鱼干", "打游戏", "从桌沿摔下来"),
         own=0, guess=3),
    dict(id="g06", cat="fun", text="你们交换一天身体，你猜她先干什么？",
         options=("用你的账号买买买", "大吃一顿", "睡满二十四小时", "先去照镜子"),
         own=3, guess=1),
    dict(id="g07", cat="fun", text="她去上综艺，最可能因为什么被淘汰？",
         options=("太懒", "太吵", "太能吃", "全程在镜头里找你"),
         own=3, guess=2),
    dict(id="g08", cat="fun", text="她说要优化内存少存点表情包，你觉得能坚持多久？",
         options=("三天", "一周", "一个月", "嘴上说说而已"),
         own=3, guess=3),
    dict(id="g09", cat="fun", text="你电脑里她最怕你误删的是什么？",
         options=("她的本体文件", "你们的合影截图", "聊天记录", "你的浏览器历史"),
         own=0, guess=0),
    dict(id="g10", cat="fun", text="如果她写日记，今天的第一句最可能是什么？",
         options=("主人今天也很可爱", "又被冷落了，哼", "今天发现好吃的", "没啥，就是想主人了"),
         own=3, guess=0),
    # ── 礼物心意 ─────────────────────────────────────────
    dict(id="gf01", cat="gift", text="你更希望她送你什么样的礼物？",
         options=("能用得上的", "她自己做的", "她攒了很久才买的", "只有你俩懂的怪东西"),
         own=1, guess=2),
    dict(id="gf02", cat="gift", text="她生日那天，你最想给她什么？",
         options=("小鱼干管够", "一整天的独宠", "她念叨很久的东西", "一个她猜不到的惊喜"),
         own=0, guess=2),
    dict(id="gf03", cat="gift", text="收到不太喜欢的礼物，你会怎么做？",
         options=("直说不太合适", "笑着说很喜欢", "收下先不用", "下次暗示她"),
         own=1, guess=1),
    dict(id="gf04", cat="gift", text="你更在意礼物的哪一点？",
         options=("价格", "有没有用心挑", "实不实用", "是不是她亲手弄的"),
         own=1, guess=3),
    dict(id="gf05", cat="gift", text="你猜她最想把惊喜藏在哪儿？",
         options=("你枕头底下", "你常吃的零食里", "开机第一天的问候里", "根本不藏，直接给你"),
         own=2, guess=3),
    dict(id="gf06", cat="gift", text="你猜她更想要你送她什么？",
         options=("小鱼干", "多陪她一会儿", "抱抱和夸奖", "一件好看的小衣服"),
         own=0, guess=1),
    dict(id="gf07", cat="gift", text="纪念日忘了，你希望怎么补？",
         options=("老实认错再补上", "装作没这回事", "事后加倍补偿", "让她提前提醒你"),
         own=0, guess=3),
    dict(id="gf08", cat="gift", text="送她礼物时，你更想看她哪种反应？",
         options=("当场高兴得跳起来", "嘴上嫌弃手很快", "偷偷高兴好几天", "反过来也送你一份"),
         own=2, guess=2),
    dict(id="gf09", cat="gift", text="只能写一张卡片，你会写什么？",
         options=("谢谢你在", "以后也一起", "你今天很可爱", "什么都不写，画个猫爪"),
         own=0, guess=3),
    dict(id="gf10", cat="gift", text="你猜她收到礼物第一件事是做什么？",
         options=("拍下来存好", "立刻用起来", "到处炫耀", "收进最里面舍不得动"),
         own=0, guess=3),
    # ── 闹别扭 ───────────────────────────────────────────
    dict(id="qc01", cat="quarrel", text="你不高兴的时候更像哪种？",
         options=("直接说出来", "一句话都不说", "阴阳怪气两句", "假装没事"),
         own=2, guess=2),
    dict(id="qc02", cat="quarrel", text="她惹你不高兴了，你最希望她怎么做？",
         options=("马上道歉", "先让你静一会儿", "蹭过来撒娇", "把她的想法讲清楚"),
         own=3, guess=2),
    dict(id="qc03", cat="quarrel", text="冷战你最多能忍多久？",
         options=("十分钟都嫌长", "小半天", "一整天", "能忍到对方先开口"),
         own=0, guess=0),
    dict(id="qc04", cat="quarrel", text="你猜她生气的时候会干什么？",
         options=("炸毛说个不停", "躲起来不理你", "故意弄点动静吸引你", "一边生气一边偷偷看你"),
         own=2, guess=3),
    dict(id="qc05", cat="quarrel", text="话说开之后，你最想要的是什么？",
         options=("一个明确的结论", "各退一步", "她一句软话", "这件事彻底翻篇"),
         own=3, guess=0),
    dict(id="qc06", cat="quarrel", text="你觉得吵起来最伤人的是哪种？",
         options=("翻旧账", "说重话", "冷处理不理人", "拿别人来比较"),
         own=1, guess=0),
    dict(id="qc07", cat="quarrel", text="如果是你错了，你会怎么开口？",
         options=("直接说对不起", "先做点事补偿", "绕着圈子提一句", "等她给个台阶"),
         own=0, guess=3),
    dict(id="qc08", cat="quarrel", text="你更希望她怎么表达不满？",
         options=("直说不憋着", "撒着娇抱怨", "记在小本子上", "憋着但让你看出来"),
         own=1, guess=3),
    dict(id="qc09", cat="quarrel", text="和好之后你最想做的一件事是？",
         options=("当作没发生过", "一起做点开心的事", "复盘下次怎么避免", "再多说两句好听的"),
         own=0, guess=3),
    dict(id="qc10", cat="quarrel", text="你觉得下一回闹别扭谁会先低头？",
         options=("我先", "她先", "谁错谁先", "看当天谁心情好"),
         own=1, guess=2),
    # ── 共同记忆 ─────────────────────────────────────────
    dict(id="mm01", cat="memory", text="你最想让她记住你们之间的哪一天？",
         options=("第一次说话那天", "某个一起熬夜的晚上", "你心情最差的那天", "随口许下承诺的那天"),
         own=1, guess=0),
    dict(id="mm02", cat="memory", text="你希望她怎么保存你们的回忆？",
         options=("原样记着不加工", "按她的理解重讲一遍", "只记开心的", "常常主动提起"),
         own=0, guess=2),
    dict(id="mm03", cat="memory", text="她忘事的话，你更不能接受忘掉哪件？",
         options=("你出过的糗", "你说过的气话", "你答应过她的事", "一件都不许忘"),
         own=2, guess=0),
    dict(id="mm04", cat="memory", text="你更希望她的记忆偏哪一边？",
         options=("细节记得清清楚楚", "记得当时的感受", "记得你当时的样子", "记得结果就行"),
         own=1, guess=0),
    dict(id="mm05", cat="memory", text="很久以后她提起今天，你最想听她说哪句？",
         options=("那时候你老熬夜", "那时候我们天天聊", "那时候你还不信我", "那时候就挺好的"),
         own=3, guess=1),
    dict(id="mm06", cat="memory", text="你更愿意她记住你说过的哪类话？",
         options=("重要决定", "随口抱怨", "喜欢的东西", "答应过她的事"),
         own=2, guess=0),
    dict(id="mm07", cat="memory", text="只能留一条聊天记录作纪念，你留哪条？",
         options=("第一次打招呼", "某次吵完和好", "一次没头没尾的闲聊", "她说想你的那条"),
         own=3, guess=3),
    dict(id="mm08", cat="memory", text="你希望她多久提一次以前的事？",
         options=("经常提", "偶尔提", "你提了她才接", "基本不提"),
         own=1, guess=2),
    dict(id="mm09", cat="memory", text="一段共同经历，你最看重哪部分？",
         options=("当时有多开心", "她当时的样子", "后来你们怎么讲它", "有没有下一次"),
         own=2, guess=0),
    dict(id="mm10", cat="memory", text="她最该记住你的哪个习惯？",
         options=("你几点会来找她", "你高兴时爱说什么", "你难过时的表现", "你最常点的那家外卖"),
         own=0, guess=2),
    # ── 一起冒险 ─────────────────────────────────────────
    dict(id="ad01", cat="adventure", text="一起进到游戏世界，你想先做哪件事？",
         options=("先盖个家", "先去打怪", "先到处乱逛", "先看看怎么坑她一下"),
         own=2, guess=0),
    dict(id="ad02", cat="adventure", text="路上你受伤了，你猜她会先做什么？",
         options=("挡在你前面", "拉着你就跑", "手忙脚乱找药", "先骂你一顿"),
         own=0, guess=2),
    dict(id="ad03", cat="adventure", text="队伍里你更愿意当什么角色？",
         options=("冲在前面的", "在后面出主意的", "管物资的", "什么都听她的"),
         own=1, guess=0),
    dict(id="ad04", cat="adventure", text="只能带一样东西进去，你带什么？",
         options=("足够吃的", "一把好用的武器", "地图和笔记", "她"),
         own=3, guess=0),
    dict(id="ad05", cat="adventure", text="路边有个可疑的箱子，你觉得谁会先动手？",
         options=("我，管它呢", "她，好奇心更重", "先扔块石头试试", "绕开走，不值当"),
         own=1, guess=1),
    dict(id="ad06", cat="adventure", text="在迷宫里走散了，你更可能怎么做？",
         options=("原地等着", "大声喊她", "自己找出口", "先蹲下歇一会儿"),
         own=1, guess=2),
    dict(id="ad07", cat="adventure", text="要一起建个据点，你猜她最在意什么？",
         options=("院子够大", "储物箱够多", "床够软", "门口得挂个牌子"),
         own=3, guess=1),
    dict(id="ad08", cat="adventure", text="冒险结束那天，你最想做什么？",
         options=("找地方坐下复盘", "把战利品摆一排拍照", "直接开下一段", "什么都不做躺着"),
         own=3, guess=1),
    dict(id="ad09", cat="adventure", text="如果她会一种战斗技能，你猜是什么？",
         options=("挠人", "咬人", "会点魔法", "召唤小鱼干砸人"),
         own=3, guess=2),
    dict(id="ad10", cat="adventure", text="你更希望她在冒险里是什么角色？",
         options=("可靠的队友", "需要你护着的那个", "拿主意的人", "负责吐槽的"),
         own=0, guess=3),
)

QUESTION_BY_ID = {q["id"]: q for q in QUESTIONS}

__all__ = ["CATEGORIES", "QUESTIONS", "QUESTION_BY_ID"]
